/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LRU_cache;

import org.junit.Test;

import jdk.jfr.Timestamp;

import static org.junit.Assert.*;
import java.util.LinkedHashMap;
import java.util.Map;

// テストコード
public class AppTest {
    LRUcache lrucache = new LRUcache(2);

    // エントリの最大数を格納できているかテスト
    @Test
    public void _エントリの最大数の確認() throws Exception {
        assertEquals(2, lrucache.capacity);
    }

    // エントリのセットをできているかテスト
    @Test
    public void _エントリのセットを確認() throws Exception {
        lrucache.put("テスト", 1);
        assertEquals(true, lrucache.print("テスト"));
    }

    // エントリのvalueを取得できているかテスト
    @Test
    public void _エントリのvalueを取得() throws Exception {
        lrucache.put("テスト", 1);
        assertEquals(1, lrucache.get("テスト"));
    }

    // エントリの削除をテスト
    @Test
    public void _エントリを削除() throws Exception {
        lrucache.put("テスト", 1);
        lrucache.remove("テスト");
        assertEquals(-1, lrucache.get("テスト"));
    }

    // エントリが最大数に達した際のテスト
    @Test
    public void _最大数の達した時() throws Exception {
        lrucache.put("テスト", 1);
        lrucache.put("アイス", 2);
        lrucache.put("イチゴ", 1);
        assertEquals(-1, lrucache.get("テスト"));
    }

    // エントリを参照した際のテスト
    @Test
    public void _順番の更新() throws Exception {
        lrucache.put("テスト", 1);
        lrucache.put("アイス", 2);
        lrucache.get("テスト");
        lrucache.put("イチゴ", 1);
        assertEquals(1, lrucache.get("テスト"));
        assertEquals(-1, lrucache.get("アイス"));
    }
}
