/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LRU_cache;

import org.junit.Test;

import jdk.jfr.Timestamp;

import static org.junit.Assert.*;
import java.util.LinkedHashMap;
import java.util.Map;

// テストコード
public class AppTest {
    LRUcache lrucache = new LRUcache(2);

    // エントリの最大数を格納できているかテスト
    @Test
    public void _LRUキャッシュの実行() throws Exception {
        assertEquals(2, lrucache.capacity);
    }

    // エントリのセットをできているかテスト
    @Test
    public void _エントリのセットを確認() throws Exception {
        lrucache.put("テスト", 1);
        assertEquals(true, lrucache.print("テスト"));
    }

    // エントリのvalueを取得できているかテスト
    @Test
    public void _エントリのvalueを取得() throws Exception {
        lrucache.capacity = 3;
        lrucache.put("テスト", 1);
        assertEquals(1, lrucache.get("テスト"));
    }
}
